default: &default
  adapter: postgresql
  pool: 5
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: bestow_bootstrap

# test:
#   <<: *default
#   database: facilgo_test

# integration_test:
#   <<: *default
#   database: facilgo_integration_test

# production:
#   <<: *default
#   database: facilgo